spring:
  application:
    name: optimQuery

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
        jdbc:
          "[batch_size]": 50
        "[order_inserts]": true
        "[order_updates]": true
        "[batch_versioned_data]": true
        connection:
          "[provider_disables_autocommit]": true

  jackson:
    serialization:
      write-dates-as-timestamps: false

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000
      # password:

server:
  port: 8081

logging:
  level:
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    "[org.springframework.security]": DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html


